import fs from 'fs';

const translations = {
  "From grassroots theatre to programmes at greater scale and a wider national focus.": "ਜ਼ਮੀਨੀ ਪੱਧਰ ਦੇ ਥੀਏਟਰ ਤੋਂ ਲੈ ਕੇ ਵੱਡੇ ਪੱਧਰ 'ਤੇ ਪ੍ਰੋਗਰਾਮਾਂ ਅਤੇ ਵਿਆਪਕ ਰਾਸ਼ਟਰੀ ਫੋਕਸ ਤੱਕ।",
  "2004 — Punjabi Samvad begins": "2004 — ਪੰਜਾਬੀ ਸੰਵਾਦ ਸ਼ੁਰੂ ਹੋਇਆ",
  "2009 — Formal registration": "2009 — ਰਸਮੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
  "2017 — Tirhayi Umar documentary and World Punjabi Conference": "2017 — ਤਿਰਹਾਈ ਉਮਰ ਡਾਕੂਮੈਂਟਰੀ ਅਤੇ ਵਿਸ਼ਵ ਪੰਜਾਬੀ ਕਾਨਫਰੰਸ",
  "Recent years — 100,000+ reached through mental-health programmes": "ਹਾਲੀਆ ਸਾਲ — ਮਾਨਸਿਕ-ਸਿਹਤ ਪ੍ਰੋਗਰਾਮਾਂ ਰਾਹੀਂ 100,000+ ਤੱਕ ਪਹੁੰਚ ਕੀਤੀ ਗਈ",
  "Today — Partnerships for a wider national reach": "ਅੱਜ — ਵਿਆਪਕ ਰਾਸ਼ਟਰੀ ਪਹੁੰਚ ਲਈ ਭਾਈਵਾਲੀ",
  "Impact summary": "ਪ੍ਰਭਾਵ ਦਾ ਸਾਰ",
  "How the work translates into numbers, community reach and institutional partnerships.": "ਕੰਮ ਕਿਵੇਂ ਸੰਖਿਆਵਾਂ, ਭਾਈਚਾਰਕ ਪਹੁੰਚ ਅਤੇ ਸੰਸਥਾਗਤ ਭਾਈਵਾਲੀ ਵਿੱਚ ਬਦਲਦਾ ਹੈ।",
  "Direct programme reach": "ਸਿੱਧੀ ਪ੍ਰੋਗਰਾਮ ਪਹੁੰਚ",
  "Across empowerment, education, health and substance-abuse awareness.": "ਸਸ਼ਕਤੀਕਰਨ, ਸਿੱਖਿਆ, ਸਿਹਤ ਅਤੇ ਨਸ਼ੀਲੇ ਪਦਾਰਥਾਂ ਦੀ ਦੁਰਵਰਤੋਂ ਬਾਰੇ ਜਾਗਰੂਕਤਾ ਵਿੱਚ।",
  "Student participation": "ਵਿਦਿਆਰਥੀਆਂ ਦੀ ਭਾਗੀਦਾਰੀ",
  "Through school sessions, internships and university programmes.": "ਸਕੂਲ ਸੈਸ਼ਨਾਂ, ਇੰਟਰਨਸ਼ਿਪਾਂ ਅਤੇ ਯੂਨੀਵਰਸਿਟੀ ਪ੍ਰੋਗਰਾਮਾਂ ਰਾਹੀਂ।",
  "Institutional partners": "ਸੰਸਥਾਗਤ ਭਾਈਵਾਲ",
  "Including State Bank of India, Yes Bank, HDFC Securities and university bodies.": "ਸਟੇਟ ਬੈਂਕ ਆਫ਼ ਇੰਡੀਆ (State Bank of India), ਯੈੱਸ ਬੈਂਕ (Yes Bank), ਐਚਡੀਐਫਸੀ ਸਿਕਿਓਰਿਟੀਜ਼ (HDFC Securities) ਅਤੇ ਯੂਨੀਵਰਸਿਟੀ ਸੰਸਥਾਵਾਂ ਸਮੇਤ।",
  "Years of community work": "ਭਾਈਚਾਰਕ ਕੰਮ ਦੇ ਸਾਲ",
  "A sustained presence since the early work of Amit Bawa and Jyoti Bawa.": "ਅਮਿਤ ਬਾਵਾ ਅਤੇ ਜੋਤੀ ਬਾਵਾ ਦੇ ਸ਼ੁਰੂਆਤੀ ਕੰਮ ਤੋਂ ਬਾਅਦ ਨਿਰੰਤਰ ਮੌਜੂਦਗੀ।",
  "Core areas": "ਮੁੱਖ ਖੇਤਰ",
  "Working across empowerment, education, public health, youth, culture and substance-abuse awareness.": "ਸਸ਼ਕਤੀਕਰਨ, ਸਿੱਖਿਆ, ਜਨਤਕ ਸਿਹਤ, ਨੌਜਵਾਨਾਂ, ਸੱਭਿਆਚਾਰ ਅਤੇ ਨਸ਼ੀਲੇ ਪਦਾਰਥਾਂ ਦੀ ਦੁਰਵਰਤੋਂ ਬਾਰੇ ਜਾਗਰੂਕਤਾ ਵਿੱਚ ਕੰਮ ਕਰਨਾ।",
  "Women & Girls": "ਔਰਤਾਂ ਅਤੇ ਕੁੜੀਆਂ",
  "Promoting education, dignity and life skills.": "ਸਿੱਖਿਆ, ਸਨਮਾਨ ਅਤੇ ਜੀਵਨ ਦੇ ਹੁਨਰ ਨੂੰ ਉਤਸ਼ਾਹਿਤ ਕਰਨਾ।",
  "Mental Health": "ਮਾਨਸਿਕ ਸਿਹਤ",
  "Making emotional well-being easier to understand.": "ਭਾਵਨਾਤਮਕ ਤੰਦਰੁਸਤੀ ਨੂੰ ਸਮਝਣਾ ਆਸਾਨ ਬਣਾਉਣਾ।",
  "Menstrual Health": "ਮਾਹਵਾਰੀ ਸਿਹਤ",
  "Practical information addressing stigma and misinformation.": "ਸਟਿਗਮਾ ਅਤੇ ਗਲਤ ਜਾਣਕਾਰੀ ਨੂੰ ਦੂਰ ਕਰਨ ਵਾਲੀ ਵਿਹਾਰਕ ਜਾਣਕਾਰੀ।",
  "Education & Youth": "ਸਿੱਖਿਆ ਅਤੇ ਨੌਜਵਾਨ",
  "Mentoring, vocational development and youth activities.": "ਸਲਾਹ, ਕਿੱਤਾਮੁਖੀ ਵਿਕਾਸ ਅਤੇ ਨੌਜਵਾਨਾਂ ਦੀਆਂ ਗਤੀਵਿਧੀਆਂ।",
  "Substance-Abuse Awareness": "ਨਸ਼ੀਲੇ ਪਦਾਰਥਾਂ ਦੀ ਦੁਰਵਰਤੋਂ ਬਾਰੇ ਜਾਗਰੂਕਤਾ",
  "Community outreach and preventive communication.": "ਕਮਿਊਨਿਟੀ ਆਊਟਰੀਚ ਅਤੇ ਰੋਕਥਾਮ ਸੰਚਾਰ।",
  "Community Health": "ਭਾਈਚਾਰਕ ਸਿਹਤ",
  "HIV/AIDS and preventive-health education.": "ਐੱਚਆਈਵੀ/ਏਡਜ਼ (HIV/AIDS) ਅਤੇ ਰੋਕਥਾਮ-ਸਿਹਤ ਸਿੱਖਿਆ।",
  "Culture & Creative Advocacy": "ਸੱਭਿਆਚਾਰ ਅਤੇ ਰਚਨਾਤਮਕ ਵਕਾਲਤ",
  "Theatre, cultural programmes and social communication.": "ਥੀਏਟਰ, ਸੱਭਿਆਚਾਰਕ ਪ੍ਰੋਗਰਾਮ ਅਤੇ ਸਮਾਜਿਕ ਸੰਚਾਰ।",
  "Next steps": "ਅਗਲੇ ਕਦਮ",
  "Current focus and future goals for Punjabi Samvad.": "ਪੰਜਾਬੀ ਸੰਵਾਦ ਲਈ ਮੌਜੂਦਾ ਫੋਕਸ ਅਤੇ ਭਵਿੱਖ ਦੇ ਟੀਚੇ।",
  "Expand institutional partnerships to take useful programmes to more communities across India.": "ਭਾਰਤ ਭਰ ਦੇ ਹੋਰ ਭਾਈਚਾਰਿਆਂ ਤੱਕ ਉਪਯੋਗੀ ਪ੍ਰੋਗਰਾਮਾਂ ਨੂੰ ਲਿਜਾਣ ਲਈ ਸੰਸਥਾਗਤ ਭਾਈਵਾਲੀ ਦਾ ਵਿਸਥਾਰ ਕਰੋ।",
  "Increase reach in mental health and menstrual health awareness among students.": "ਵਿਦਿਆਰਥੀਆਂ ਵਿੱਚ ਮਾਨਸਿਕ ਸਿਹਤ ਅਤੇ ਮਾਹਵਾਰੀ ਸਿਹਤ ਪ੍ਰਤੀ ਜਾਗਰੂਕਤਾ ਵਧਾਓ।",
  "Develop digital learning networks for youth skills and employability.": "ਨੌਜਵਾਨਾਂ ਦੇ ਹੁਨਰ ਅਤੇ ਰੁਜ਼ਗਾਰ ਯੋਗਤਾ ਲਈ ਡਿਜੀਟਲ ਸਿਖਲਾਈ ਨੈੱਟਵਰਕ ਵਿਕਸਿਤ ਕਰੋ।",
  "Continue using creative culture and documentary for social engagement.": "ਸਮਾਜਿਕ ਰੁਝੇਵਿਆਂ ਲਈ ਰਚਨਾਤਮਕ ਸੱਭਿਆਚਾਰ ਅਤੇ ਡਾਕੂਮੈਂਟਰੀ ਦੀ ਵਰਤੋਂ ਜਾਰੀ ਰੱਖੋ।",
  "Discuss a Partnership": "ਭਾਈਵਾਲੀ ਬਾਰੇ ਚਰਚਾ ਕਰੋ",
  "Tell us about your social-impact programme, target group, geography and current stage. We can explore whether Punjabi Samvad is the right implementation partner.": "ਸਾਨੂੰ ਆਪਣੇ ਸਮਾਜਿਕ-ਪ੍ਰਭਾਵ ਪ੍ਰੋਗਰਾਮ, ਟੀਚਾ ਸਮੂਹ, ਭੂਗੋਲ ਅਤੇ ਮੌਜੂਦਾ ਪੜਾਅ ਬਾਰੇ ਦੱਸੋ। ਅਸੀਂ ਇਹ ਪੜਚੋਲ ਕਰ ਸਕਦੇ ਹਾਂ ਕਿ ਕੀ ਪੰਜਾਬੀ ਸੰਵਾਦ ਸਹੀ ਲਾਗੂ ਕਰਨ ਵਾਲਾ ਭਾਈਵਾਲ ਹੈ।",
  "What are you exploring?": "ਤੁਸੀਂ ਕੀ ਪੜਚੋਲ ਕਰ ਰਹੇ ਹੋ?",
  "We welcome early conversations as well as detailed programme briefs.": "ਅਸੀਂ ਸ਼ੁਰੂਆਤੀ ਗੱਲਬਾਤ ਦੇ ਨਾਲ-ਨਾਲ ਵਿਸਤ੍ਰਿਤ ਪ੍ਰੋਗਰਾਮ ਸੰਖੇਪਾਂ ਦਾ ਸਵਾਗਤ ਕਰਦੇ ਹਾਂ।",
  "CSR partnership": "ਸੀਐਸਆਰ (CSR) ਭਾਈਵਾਲੀ",
  "Foundation grant": "ਫਾਊਂਡੇਸ਼ਨ ਗ੍ਰਾਂਟ",
  "Programme sponsorship": "ਪ੍ਰੋਗਰਾਮ ਸਪਾਂਸਰਸ਼ਿਪ",
  "Employee engagement": "ਕਰਮਚਾਰੀ ਦੀ ਸ਼ਮੂਲੀਅਤ",
  "Academic collaboration": "ਅਕਾਦਮਿਕ ਸਹਿਯੋਗ",
  "Multi-state programme": "ਬਹੁ-ਰਾਜੀ ਪ੍ਰੋਗਰਾਮ",
  "Areas of interest": "ਦਿਲਚਸਪੀ ਦੇ ਖੇਤਰ",
  "Women and girls, mental health, menstrual health, education, substance-abuse awareness, community health, culture or multiple areas.": "ਔਰਤਾਂ ਅਤੇ ਕੁੜੀਆਂ, ਮਾਨਸਿਕ ਸਿਹਤ, ਮਾਹਵਾਰੀ ਸਿਹਤ, ਸਿੱਖਿਆ, ਨਸ਼ੀਲੇ ਪਦਾਰਥਾਂ ਦੀ ਦੁਰਵਰਤੋਂ ਬਾਰੇ ਜਾਗਰੂਕਤਾ, ਭਾਈਚਾਰਕ ਸਿਹਤ, ਸੱਭਿਆਚਾਰ ਜਾਂ ਕਈ ਖੇਤਰ।",
  "Geographic scope": "ਭੂਗੋਲਿਕ ਦਾਇਰਾ",
  "One community, one state, multiple states or pan-India programmes can be discussed based on requirements and local implementation needs.": "ਲੋੜਾਂ ਅਤੇ ਸਥਾਨਕ ਲਾਗੂ ਕਰਨ ਦੀਆਂ ਜ਼ਰੂਰਤਾਂ ਦੇ ਅਧਾਰ 'ਤੇ ਇੱਕ ਭਾਈਚਾਰੇ, ਇੱਕ ਰਾਜ, ਕਈ ਰਾਜਾਂ ਜਾਂ ਪੈਨ-ਇੰਡੀਆ ਪ੍ਰੋਗਰਾਮਾਂ ਬਾਰੇ ਚਰਚਾ ਕੀਤੀ ਜਾ ਸਕਦੀ ਹੈ।",
  "Email our partnership team": "ਸਾਡੀ ਭਾਈਵਾਲੀ ਟੀਮ ਨੂੰ ਈਮੇਲ ਕਰੋ",
  "Internships & Volunteering": "ਇੰਟਰਨਸ਼ਿਪ ਅਤੇ ਵਲੰਟੀਅਰਿੰਗ",
  "University students can gain practical experience through social research, programme delivery, communication and community engagement with Punjabi Samvad.": "ਯੂਨੀਵਰਸਿਟੀ ਦੇ ਵਿਦਿਆਰਥੀ ਪੰਜਾਬੀ ਸੰਵਾਦ ਦੇ ਨਾਲ ਸਮਾਜਿਕ ਖੋਜ, ਪ੍ਰੋਗਰਾਮ ਡਿਲੀਵਰੀ, ਸੰਚਾਰ ਅਤੇ ਭਾਈਚਾਰਕ ਸ਼ਮੂਲੀਅਤ ਰਾਹੀਂ ਵਿਹਾਰਕ ਤਜਰਬਾ ਹਾਸਲ ਕਰ ਸਕਦੇ ਹਨ।",
  "Community programmes": "ਭਾਈਚਾਰਕ ਪ੍ਰੋਗਰਾਮ",
  "Support awareness sessions, outreach and programme preparation under the guidance of the Punjabi Samvad team.": "ਪੰਜਾਬੀ ਸੰਵਾਦ ਟੀਮ ਦੀ ਅਗਵਾਈ ਹੇਠ ਜਾਗਰੂਕਤਾ ਸੈਸ਼ਨਾਂ, ਆਊਟਰੀਚ ਅਤੇ ਪ੍ਰੋਗਰਾਮ ਦੀ ਤਿਆਰੀ ਦਾ ਸਮਰਥਨ ਕਰੋ।",
  "Research and documentation": "ਖੋਜ ਅਤੇ ਦਸਤਾਵੇਜ਼ੀਕਰਨ",
  "Assist with background research, programme records, participant feedback and material for future planning.": "ਭਵਿੱਖ ਦੀ ਯੋਜਨਾਬੰਦੀ ਲਈ ਪਿਛੋਕੜ ਖੋਜ, ਪ੍ਰੋਗਰਾਮ ਰਿਕਾਰਡ, ਭਾਗੀਦਾਰਾਂ ਦੇ ਫੀਡਬੈਕ ਅਤੇ ਸਮੱਗਰੀ ਵਿੱਚ ਸਹਾਇਤਾ ਕਰੋ।",
  "Literature and communication": "ਸਾਹਿਤ ਅਤੇ ਸੰਚਾਰ",
  "Contribute to literary campaigns, cultural work, educational material and digital awareness.": "ਸਾਹਿਤਕ ਮੁਹਿੰਮਾਂ, ਸੱਭਿਆਚਾਰਕ ਕੰਮ, ਵਿਦਿਅਕ ਸਮੱਗਰੀ ਅਤੇ ਡਿਜੀਟਲ ਜਾਗਰੂਕਤਾ ਵਿੱਚ ਯੋਗਦਾਨ ਪਾਓ।",
  "Volunteer and professional support": "ਵਲੰਟੀਅਰ ਅਤੇ ਪੇਸ਼ੇਵਰ ਸਹਾਇਤਾ",
  "People with relevant time or expertise may support events, training, health education, arts and programme planning.": "ਢੁਕਵੇਂ ਸਮੇਂ ਜਾਂ ਮੁਹਾਰਤ ਵਾਲੇ ਲੋਕ ਸਮਾਗਮਾਂ, ਸਿਖਲਾਈ, ਸਿਹਤ ਸਿੱਖਿਆ, ਕਲਾ ਅਤੇ ਪ੍ਰੋਗਰਾਮ ਦੀ ਯੋਜਨਾਬੰਦੀ ਦਾ ਸਮਰਥਨ ਕਰ ਸਕਦੇ ਹਨ।",
  "Apply or enquire": "ਅਪਲਾਈ ਕਰੋ ਜਾਂ ਪੁੱਛਗਿੱਛ ਕਰੋ",
  "Support Our Work": "ਸਾਡੇ ਕੰਮ ਦਾ ਸਮਰਥਨ ਕਰੋ",
  "Donations help sustain current work and extend programmes where additional resources are available.": "ਦਾਨ ਮੌਜੂਦਾ ਕੰਮ ਨੂੰ ਕਾਇਮ ਰੱਖਣ ਅਤੇ ਪ੍ਰੋਗਰਾਮਾਂ ਨੂੰ ਵਧਾਉਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ ਜਿੱਥੇ ਵਾਧੂ ਸਰੋਤ ਉਪਲਬਧ ਹਨ।",
  "Support a specific programme": "ਇੱਕ ਖਾਸ ਪ੍ਰੋਗਰਾਮ ਦਾ ਸਮਰਥਨ ਕਰੋ",
  "Choose an area aligned with your interests and discuss current priorities with us.": "ਆਪਣੀਆਂ ਦਿਲਚਸਪੀਆਂ ਦੇ ਅਨੁਕੂਲ ਇੱਕ ਖੇਤਰ ਚੁਣੋ ਅਤੇ ਸਾਡੇ ਨਾਲ ਮੌਜੂਦਾ ਤਰਜੀਹਾਂ ਬਾਰੇ ਚਰਚਾ ਕਰੋ।",
  "Support where needed": "ਜਿੱਥੇ ਲੋੜ ਹੋਵੇ ਉੱਥੇ ਸਹਾਇਤਾ ਕਰੋ",
  "Unrestricted contributions allow flexibility to respond to current programme and organisational needs.": "ਨਿਰਵਿਘਨ ਯੋਗਦਾਨ ਮੌਜੂਦਾ ਪ੍ਰੋਗਰਾਮ ਅਤੇ ਸੰਗਠਨਾਤਮਕ ਲੋੜਾਂ ਦਾ ਜਵਾਬ ਦੇਣ ਲਈ ਲਚਕਤਾ ਪ੍ਰਦਾਨ ਕਰਦੇ ਹਨ।",
  "CSR & institutional funding": "ਸੀਐਸਆਰ (CSR) ਅਤੇ ਸੰਸਥਾਗਤ ਫੰਡਿੰਗ",
  "Structured partnerships can support clearly defined programmes across one or multiple locations.": "ਢਾਂਚਾਗਤ ਭਾਈਵਾਲੀ ਇੱਕ ਜਾਂ ਕਈ ਸਥਾਨਾਂ ਵਿੱਚ ਸਪਸ਼ਟ ਤੌਰ 'ਤੇ ਪਰਿਭਾਸ਼ਿਤ ਪ੍ਰੋਗਰਾਮਾਂ ਦਾ ਸਮਰਥਨ ਕਰ ਸਕਦੀ ਹੈ।",
  "80G approval": "80G ਪ੍ਰਵਾਨਗੀ",
  "Eligible donations may qualify for tax benefits under applicable provisions. Please consult your tax adviser.": "ਯੋਗ ਦਾਨ ਲਾਗੂ ਪ੍ਰਬੰਧਾਂ ਦੇ ਤਹਿਤ ਟੈਕਸ ਲਾਭਾਂ ਲਈ ਯੋਗ ਹੋ ਸਕਦੇ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਟੈਕਸ ਸਲਾਹਕਾਰ ਨਾਲ ਸਲਾਹ ਕਰੋ।",
  "Contact us to support": "ਸਮਰਥਨ ਕਰਨ ਲਈ ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
  "Gallery": "ਗੈਲਰੀ",
  "Photographs from programmes, workshops, community activities, cultural events and partnerships.": "ਪ੍ਰੋਗਰਾਮਾਂ, ਵਰਕਸ਼ਾਪਾਂ, ਭਾਈਚਾਰਕ ਗਤੀਵਿਧੀਆਂ, ਸੱਭਿਆਚਾਰਕ ਸਮਾਗਮਾਂ ਅਤੇ ਭਾਈਵਾਲੀ ਤੋਂ ਤਸਵੀਰਾਂ।",
  "Education, vocational skills and awareness activities.": "ਸਿੱਖਿਆ, ਕਿੱਤਾਮੁਖੀ ਹੁਨਰ ਅਤੇ ਜਾਗਰੂਕਤਾ ਗਤੀਵਿਧੀਆਂ।",
  "Health & Well-being": "ਸਿਹਤ ਅਤੇ ਤੰਦਰੁਸਤੀ",
  "Mental-health, menstrual-health and HIV/AIDS awareness.": "ਮਾਨਸਿਕ-ਸਿਹਤ, ਮਾਹਵਾਰੀ-ਸਿਹਤ ਅਤੇ ਐੱਚਆਈਵੀ/ਏਡਜ਼ (HIV/AIDS) ਜਾਗਰੂਕਤਾ।",
  "Lectures, seminars and community outreach.": "ਲੈਕਚਰ, ਸੈਮੀਨਾਰ ਅਤੇ ਕਮਿਊਨਿਟੀ ਆਊਟਰੀਚ।",
  "Student engagement, internships, mentoring and participation.": "ਵਿਦਿਆਰਥੀਆਂ ਦੀ ਸ਼ਮੂਲੀਅਤ, ਇੰਟਰਨਸ਼ਿਪਾਂ, ਸਲਾਹਕਾਰੀ ਅਤੇ ਭਾਗੀਦਾਰੀ।",
  "Culture & Theatre": "ਸੱਭਿਆਚਾਰ ਅਤੇ ਥੀਏਟਰ",
  "Theatre productions, cultural programmes and artistic activities.": "ਥੀਏਟਰ ਨਾਟਕ, ਸੱਭਿਆਚਾਰਕ ਪ੍ਰੋਗਰਾਮ ਅਤੇ ਕਲਾਤਮਕ ਗਤੀਵਿਧੀਆਂ।",
  "Community & Partnerships": "ਭਾਈਚਾਰਾ ਅਤੇ ਭਾਈਵਾਲੀ",
  "Grassroots work and institutional collaborations.": "ਜ਼ਮੀਨੀ ਪੱਧਰ ਦਾ ਕੰਮ ਅਤੇ ਸੰਸਥਾਗਤ ਸਹਿਯੋਗ।",
  "Explore our programmes": "ਸਾਡੇ ਪ੍ਰੋਗਰਾਮਾਂ ਦੀ ਪੜਚੋਲ ਕਰੋ",
  "News & Updates": "ਖ਼ਬਰਾਂ ਅਤੇ ਅੱਪਡੇਟ",
  "Latest news and activities from Punjabi Samvad.": "ਪੰਜਾਬੀ ਸੰਵਾਦ ਤੋਂ ਤਾਜ਼ਾ ਖ਼ਬਰਾਂ ਅਤੇ ਗਤੀਵਿਧੀਆਂ।",
  "Mental-Health Awareness in Schools": "ਸਕੂਲਾਂ ਵਿੱਚ ਮਾਨਸਿਕ ਸਿਹਤ ਪ੍ਰਤੀ ਜਾਗਰੂਕਤਾ",
  "Making emotional well-being easier for young people to understand and discuss.": "ਨੌਜਵਾਨਾਂ ਲਈ ਭਾਵਨਾਤਮਕ ਤੰਦਰੁਸਤੀ ਨੂੰ ਸਮਝਣਾ ਅਤੇ ਚਰਚਾ ਕਰਨਾ ਆਸਾਨ ਬਣਾਉਣਾ।",
  "100,000+ reached": "100,000+ ਪਹੁੰਚੇ",
  "Menstrual-Health Awareness": "ਮਾਹਵਾਰੀ-ਸਿਹਤ ਜਾਗਰੂਕਤਾ",
  "15,000+ reached": "15,000+ ਪਹੁੰਚੇ",
  "Anti-Drug Awareness in Rural Communities": "ਪੇਂਡੂ ਭਾਈਚਾਰਿਆਂ ਵਿੱਚ ਨਸ਼ਾ ਵਿਰੋਧੀ ਜਾਗਰੂਕਤਾ",
  "Grassroots lectures and Tirhayi Umar communicate the human impact of substance abuse.": "ਜ਼ਮੀਨੀ ਪੱਧਰ ਦੇ ਲੈਕਚਰ ਅਤੇ ਤਿਰਹਾਈ ਉਮਰ ਨਸ਼ੀਲੇ ਪਦਾਰਥਾਂ ਦੀ ਦੁਰਵਰਤੋਂ ਦੇ ਮਨੁੱਖੀ ਪ੍ਰਭਾਵ ਨੂੰ ਸੰਚਾਰ ਕਰਦੇ ਹਨ।",
  "52,000+ reached": "52,000+ ਪਹੁੰਚੇ",
  "Theatre addressing female foeticide, discrimination and dignity.": "ਮਾਦਾ ਭਰੂਣ ਹੱਤਿਆ, ਵਿਤਕਰੇ ਅਤੇ ਸਨਮਾਨ ਨੂੰ ਸੰਬੋਧਿਤ ਕਰਦਾ ਥੀਏਟਰ।",
  "1,100,000+ reached": "1,100,000+ ਪਹੁੰਚੇ",
  "Education for Girls": "ਕੁੜੀਆਂ ਲਈ ਸਿੱਖਿਆ",
  "Educational support and initiatives intended to reduce barriers to learning.": "ਸਿੱਖਣ ਦੀਆਂ ਰੁਕਾਵਟਾਂ ਨੂੰ ਘਟਾਉਣ ਦੇ ਇਰਾਦੇ ਨਾਲ ਵਿਦਿਅਕ ਸਹਾਇਤਾ ਅਤੇ ਪਹਿਲਕਦਮੀਆਂ।",
  "Punjabi Culture & Youth": "ਪੰਜਾਬੀ ਸੱਭਿਆਚਾਰ ਅਤੇ ਨੌਜਵਾਨ",
  "Creative platforms connecting young people with Punjabi heritage.": "ਨੌਜਵਾਨਾਂ ਨੂੰ ਪੰਜਾਬੀ ਵਿਰਸੇ ਨਾਲ ਜੋੜਨ ਵਾਲੇ ਰਚਨਾਤਮਕ ਪਲੇਟਫਾਰਮ।",
  "Transparency & Compliance": "ਪਾਰਦਰਸ਼ਤਾ ਅਤੇ ਪਾਲਣਾ",
  "Clear information about Punjabi Samvad’s legal status, registrations and approvals.": "ਪੰਜਾਬੀ ਸੰਵਾਦ ਦੀ ਕਾਨੂੰਨੀ ਸਥਿਤੀ, ਰਜਿਸਟ੍ਰੇਸ਼ਨਾਂ ਅਤੇ ਪ੍ਰਵਾਨਗੀਆਂ ਬਾਰੇ ਸਪੱਸ਼ਟ ਜਾਣਕਾਰੀ।",
  "Organisation details": "ਸੰਸਥਾ ਦੇ ਵੇਰਵੇ",
  "Registered under the Societies Registration Act, 1860.": "ਸੁਸਾਇਟੀਜ਼ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਐਕਟ, 1860 ਦੇ ਤਹਿਤ ਰਜਿਸਟਰਡ।",
  "Registration No. 75": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਨੰਬਰ 75",
  "Registered 02 July 2009": "ਰਜਿਸਟਰਡ 02 ਜੁਲਾਈ 2009",
  "PAN: AACAP2577N": "ਪੈਨ: AACAP2577N",
  "NGO Darpan: PB/2017/0156494": "ਐੱਨਜੀਓ ਦਰਪਣ: PB/2017/0156494",
  "CSR Registration: CSR00032253": "ਸੀਐਸਆਰ (CSR) ਰਜਿਸਟ੍ਰੇਸ਼ਨ: CSR00032253",
  "Registered office: 293, Green Avenue, Amritsar, Punjab 143001": "ਰਜਿਸਟਰਡ ਦਫ਼ਤਰ: 293, ਗ੍ਰੀਨ ਐਵੇਨਿਊ, ਅੰਮ੍ਰਿਤਸਰ, ਪੰਜਾਬ 143001",
  "12AB Registration": "12AB ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
  "Granted under Section 12AB(1)(b).": "ਸੈਕਸ਼ਨ 12AB(1)(b) ਦੇ ਤਹਿਤ ਪ੍ਰਦਾਨ ਕੀਤੀ ਗਈ।",
  "Registration: AACAP2577N25CD01": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ: AACAP2577N25CD01",
  "Approval date: 06 March 2026": "ਪ੍ਰਵਾਨਗੀ ਦੀ ਮਿਤੀ: 06 ਮਾਰਚ 2026",
  "Assessment years: 2027–28 to 2036–37": "ਮੁਲਾਂਕਣ ਸਾਲ: 2027-28 ਤੋਂ 2036-37",
  "80G Approval": "80G ਪ੍ਰਵਾਨਗੀ",
  "Approved under Section 80G(5).": "ਸੈਕਸ਼ਨ 80G(5) ਦੇ ਅਧੀਨ ਮਨਜ਼ੂਰ।",
  "Approval: AACAP2577N25CD01": "ਪ੍ਰਵਾਨਗੀ: AACAP2577N25CD01",
  "Approval date: 06 March 2026": "ਪ੍ਰਵਾਨਗੀ ਦੀ ਮਿਤੀ: 06 ਮਾਰਚ 2026",
  "Assessment years: 2027–28 to 2031–32": "ਮੁਲਾਂਕਣ ਸਾਲ: 2027-28 ਤੋਂ 2031-32",
  "Documents": "ਦਸਤਾਵੇਜ਼",
  "Registration certificate, CSR registration, NGO Darpan registration, 12AB and 80G approval orders are maintained by the organisation.": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਰਟੀਫਿਕੇਟ, ਸੀਐਸਆਰ ਰਜਿਸਟ੍ਰੇਸ਼ਨ, ਐਨਜੀਓ ਦਰਪਣ ਰਜਿਸਟ੍ਰੇਸ਼ਨ, 12AB ਅਤੇ 80G ਮਨਜ਼ੂਰੀ ਆਦੇਸ਼ ਸੰਸਥਾ ਦੁਆਰਾ ਰੱਖੇ ਜਾਂਦੇ ਹਨ।",
  "Request information": "ਜਾਣਕਾਰੀ ਦੀ ਬੇਨਤੀ ਕਰੋ",
  "Frequently Asked Questions": "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ",
  "Quick answers about Punjabi Samvad, our programmes, partnerships and ways to contribute.": "ਪੰਜਾਬੀ ਸੰਵਾਦ, ਸਾਡੇ ਪ੍ਰੋਗਰਾਮਾਂ, ਭਾਈਵਾਲੀ ਅਤੇ ਯੋਗਦਾਨ ਪਾਉਣ ਦੇ ਤਰੀਕਿਆਂ ਬਾਰੇ ਤੁਰੰਤ ਜਵਾਬ।",
  "What is Punjabi Samvad?": "ਪੰਜਾਬੀ ਸੰਵਾਦ ਕੀ ਹੈ?",
  "A national NGO headquartered in Amritsar working across empowerment, education, mental health, menstrual health, youth, substance-abuse awareness, HIV/AIDS and culture.": "ਅੰਮ੍ਰਿਤਸਰ ਵਿੱਚ ਹੈੱਡਕੁਆਰਟਰ ਵਾਲੀ ਇੱਕ ਰਾਸ਼ਟਰੀ ਐਨਜੀਓ ਜੋ ਸਸ਼ਕਤੀਕਰਨ, ਸਿੱਖਿਆ, ਮਾਨਸਿਕ ਸਿਹਤ, ਮਾਹਵਾਰੀ ਸਿਹਤ, ਨੌਜਵਾਨ, ਨਸ਼ੀਲੇ ਪਦਾਰਥਾਂ ਦੀ ਦੁਰਵਰਤੋਂ ਜਾਗਰੂਕਤਾ, ਐਚਆਈਵੀ/ਏਡਜ਼ (HIV/AIDS) ਅਤੇ ਸੱਭਿਆਚਾਰ ਵਿੱਚ ਕੰਮ ਕਰਦੀ ਹੈ।",
  "When did Punjabi Samvad begin?": "ਪੰਜਾਬੀ ਸੰਵਾਦ ਕਦੋਂ ਸ਼ੁਰੂ ਹੋਇਆ?",
  "The journey began in 2004 with Amit Bawa and Jyoti Bawa. Formal registration followed on 02 July 2009.": "ਸਫ਼ਰ 2004 ਵਿੱਚ ਅਮਿਤ ਬਾਵਾ ਅਤੇ ਜੋਤੀ ਬਾਵਾ ਨਾਲ ਸ਼ੁਰੂ ਹੋਇਆ ਸੀ। ਰਸਮੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ 02 ਜੁਲਾਈ 2009 ਨੂੰ ਹੋਈ।",
  "Where do you work?": "ਤੁਸੀਂ ਕਿੱਥੇ ਕੰਮ ਕਰਦੇ ਹੋ?",
  "Our grassroots experience is rooted in Punjab, while we welcome partnerships with a wider national and multi-state focus.": "ਸਾਡਾ ਜ਼ਮੀਨੀ ਤਜ਼ਰਬਾ ਪੰਜਾਬ ਵਿੱਚ ਜੜ੍ਹਿਆ ਹੋਇਆ ਹੈ, ਜਦੋਂ ਕਿ ਅਸੀਂ ਇੱਕ ਵਿਸ਼ਾਲ ਰਾਸ਼ਟਰੀ ਅਤੇ ਬਹੁ-ਰਾਜੀ ਫੋਕਸ ਨਾਲ ਭਾਈਵਾਲੀ ਦਾ ਸਵਾਗਤ ਕਰਦੇ ਹਾਂ।",
  "Can companies partner for CSR programmes?": "ਕੀ ਕੰਪਨੀਆਂ ਸੀਐਸਆਰ (CSR) ਪ੍ਰੋਗਰਾਮਾਂ ਲਈ ਭਾਈਵਾਲੀ ਕਰ ਸਕਦੀਆਂ ਹਨ?",
  "Yes. Punjabi Samvad holds CSR Registration No. CSR00032253.": "ਹਾਂ। ਪੰਜਾਬੀ ਸੰਵਾਦ ਕੋਲ ਸੀਐਸਆਰ (CSR) ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਨੰਬਰ CSR00032253 ਹੈ।",
  "Can I fund a specific programme?": "ਕੀ ਮੈਂ ਕਿਸੇ ਖਾਸ ਪ੍ਰੋਗਰਾਮ ਲਈ ਫੰਡ ਦੇ ਸਕਦਾ ਹਾਂ?",
  "Yes, depending on current priorities. Contact us to discuss the work you want to support.": "ਹਾਂ, ਮੌਜੂਦਾ ਤਰਜੀਹਾਂ ਦੇ ਅਧਾਰ 'ਤੇ। ਤੁਸੀਂ ਜਿਸ ਕੰਮ ਦਾ ਸਮਰਥਨ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ ਉਸ ਬਾਰੇ ਚਰਚਾ ਕਰਨ ਲਈ ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।",
  "Do you accept volunteers and interns?": "ਕੀ ਤੁਸੀਂ ਵਲੰਟੀਅਰਾਂ ਅਤੇ ਇੰਟਰਨਾਂ ਨੂੰ ਸਵੀਕਾਰ ਕਰਦੇ ਹੋ?",
  "Yes, subject to current programmes, locations and requirements.": "ਹਾਂ, ਮੌਜੂਦਾ ਪ੍ਰੋਗਰਾਮਾਂ, ਸਥਾਨਾਂ ਅਤੇ ਜ਼ਰੂਰਤਾਂ ਦੇ ਅਧੀਨ।",
  "Do you have 80G approval?": "ਕੀ ਤੁਹਾਡੇ ਕੋਲ 80G ਮਨਜ਼ੂਰੀ ਹੈ?",
  "Ask another question": "ਇੱਕ ਹੋਰ ਸਵਾਲ ਪੁੱਛੋ",
  "Contact Punjabi Samvad": "ਪੰਜਾਬੀ ਸੰਵਾਦ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
  "Discuss a programme, partnership, donation, volunteer opportunity, internship or general enquiry.": "ਕਿਸੇ ਪ੍ਰੋਗਰਾਮ, ਭਾਈਵਾਲੀ, ਦਾਨ, ਵਲੰਟੀਅਰ ਦੇ ਮੌਕੇ, ਇੰਟਰਨਸ਼ਿਪ ਜਾਂ ਆਮ ਪੁੱਛਗਿੱਛ ਬਾਰੇ ਚਰਚਾ ਕਰੋ।",
  "Registered office": "ਰਜਿਸਟਰਡ ਦਫ਼ਤਰ",
  "293, Green Avenue\nAmritsar, Punjab 143001\nIndia": "293, ਗ੍ਰੀਨ ਐਵੇਨਿਊ\nਅੰਮ੍ਰਿਤਸਰ, ਪੰਜਾਬ 143001\nਭਾਰਤ",
  "Phone & email": "ਫ਼ੋਨ ਅਤੇ ਈਮੇਲ",
  "+91 87280 33911\npunjabisamvadasr@gmail.com": "+91 87280 33911\npunjabisamvadasr@gmail.com",
  "Contact person": "ਸੰਪਰਕ ਵਿਅਕਤੀ",
  "Jyoti Bawa\nPresident, Punjabi Samvad": "ਜੋਤੀ ਬਾਵਾ\nਪ੍ਰਧਾਨ, ਪੰਜਾਬੀ ਸੰਵਾਦ",
  "What can you help with?": "ਤੁਸੀਂ ਕਿਸ ਚੀਜ਼ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦੇ ਹੋ?",
  "CSR partnership, institutional collaboration, national programmes, volunteering, internships, programme information, support, media or events.": "ਸੀਐਸਆਰ (CSR) ਭਾਈਵਾਲੀ, ਸੰਸਥਾਗਤ ਸਹਿਯੋਗ, ਰਾਸ਼ਟਰੀ ਪ੍ਰੋਗਰਾਮ, ਵਲੰਟੀਅਰਿੰਗ, ਇੰਟਰਨਸ਼ਿਪ, ਪ੍ਰੋਗਰਾਮ ਦੀ ਜਾਣਕਾਰੀ, ਸਹਾਇਤਾ, ਮੀਡੀਆ ਜਾਂ ਸਮਾਗਮ।",
  "Send an email": "ਇੱਕ ਈਮੇਲ ਭੇਜੋ"
};

let content = fs.readFileSync('src/context/LanguageContext.tsx', 'utf8');
for (const [eng, pa] of Object.entries(translations)) {
  const safeEng = eng.replace(/"/g, '\\"').replace(/\n/g, '\\n');
  const safePa = pa.replace(/"/g, '\\"').replace(/\n/g, '\\n');
  
  if (!content.includes(`"${safeEng}": {`)) {
    const insertionMarker = '\n};\n\nconst LanguageContext = createContext';
    const insertionIndex = content.indexOf(insertionMarker);
    if (insertionIndex !== -1) {
      content = content.slice(0, insertionIndex) + `,\n  "${safeEng}": {\n    en: "${safeEng}",\n    pa: "${safePa}"\n  }` + content.slice(insertionIndex);
    }
  }
}
fs.writeFileSync('src/context/LanguageContext.tsx', content);
console.log("Injected pages.ts strings");
