export type PageSection = { title: string; body: string; bullets?: string[]; stat?: string };
export type SitePage = { eyebrow: string; title: string; intro: string; sections: PageSection[]; cta?: { label: string; href: string } };

export const pages: Record<string, SitePage> = {
  "skills-livelihoods": {eyebrow:"Skills and livelihoods",title:"Skills & Livelihoods",intro:"Practical vocational training and participant stories from livelihood programmes delivered by Punjabi Samvad with CMS Foundation.",sections:[
    {title:"Practical training",body:"Training includes soap making, traditional masala preparation, spice-quality checks, Phulkari embroidery, street-food preparation and vermicomposting."},
    {title:"Stories of change",body:"Consented participant accounts document home-based income, self-employment, recovery support, children returning to school and ambitions for future work."},
    {title:"President’s field note",body:"Jyoti Bawa explains why Punjabi Samvad extended some workshops from ten days to 20–25 days and continued to guide participants after the sessions."}
  ],cta:{label:"Support vocational learning",href:"/donate"}},
  p2e: {eyebrow:"Digital learning",title:"Passport to Earning",intro:"Free, job-relevant digital learning for young people through UNICEF’s Passport to Earning platform.",sections:[]},
  kym: {eyebrow:"Financial literacy",title:"Know Your Money",intro:"Free, practical financial learning from HDFC Securities and Wagons Skill Foundation.",sections:[]},
  "media-features": {eyebrow:"Stories & coverage",title:"Media Features",intro:"Photographs from our work and selected features that document Punjabi Samvad’s journey across health, education, culture and community action.",sections:[]},
  supporters: {eyebrow:"People who stand with us",title:"Key Supporters of Punjabi Samvad",intro:"People who support Punjabi Samvad through donations, expertise, resources, connections and practical help.",sections:[]},
  "amit-bawa": {eyebrow:"Co-founder",title:"Amit Bawa",intro:"Founding inspiration behind Punjabi Samvad.",sections:[]},
  donate: {eyebrow:"Support the work",title:"Donate",intro:"Your contribution helps Punjabi Samvad take education, awareness and community programmes to more people.",sections:[]},
  about: { eyebrow:"Who we are", title:"About Punjabi Samvad", intro:"Punjabi Samvad is a national non-governmental organisation rooted in Punjab. We work with people and institutions to address social issues through education, public awareness, community participation and creative communication.", sections:[
    {title:"Our roots",body:"Punjabi Samvad began in 2004, when Amit Bawa and Jyoti Bawa decided to respond to gender discrimination and other social concerns they saw around them. The organisation was formally registered in 2009. What started as a local effort in Punjab has grown into more than two decades of sustained work with women, children, young people, schools, communities and institutions."},
    {title:"Dialogue is our starting point",body:"Samvad means dialogue. For us, dialogue is not a slogan. It is a practical way to help people speak about subjects that are often ignored, misunderstood or surrounded by stigma. A school session, village meeting, theatre performance or health workshop can all create the same opening: a place to ask honest questions and receive useful information without judgement."},
    {title:"What we work on",body:"Our programmes cover women and girls, education and youth development, mental health, menstrual health, substance-abuse prevention, HIV/AIDS awareness, vocational learning and Punjabi art and culture. These concerns often overlap, so we design activities around the people and circumstances involved rather than treating every issue in isolation."},
    {title:"How we work",body:"We combine grassroots outreach with workshops, expert-led sessions, theatre, documentary film, literature, internships and institutional partnerships. Each format serves a purpose. Health sessions make reliable information easier to understand. Theatre and film can bring difficult subjects into public conversation. Education, mentoring and vocational learning help turn awareness into practical opportunity.",bullets:["Listen before designing an activity","Work with credible subject experts and partners","Use language and formats suited to the audience","Track delivery, reach and participant response","Improve programmes through experience and feedback"]},
    {title:"From awareness to sustained action",body:"Awareness matters when it helps people recognise a problem, find trustworthy support or make a better-informed decision. Punjabi Samvad therefore works beyond one-time messaging wherever programme scope allows. We return to schools and communities, build relationships with local institutions and connect communication with learning, skills or access to expertise."},
    {title:"Creative advocacy",body:"Theatre, writing and film have been part of Punjabi Samvad from its early years. Khooh Bolda Hai brought female foeticide and discrimination against girls to more than 1,100,000 people. Tirhayi Umar used documentary storytelling to confront the human consequences of substance abuse. Creative work helps people engage with social realities that statistics alone cannot explain.",stat:"1,100,000+ people reached"},
    {title:"Partnership and reach",body:"Punjabi Samvad works with government bodies, schools, universities, healthcare professionals, charitable institutions and corporate foundations. Collaborations have included the Government of Punjab, the Aditya Birla Educational Trust, IIM Amritsar and the Ministry of Culture. These relationships bring together community access, technical knowledge and the resources needed to serve more people."},
    {title:"Our vision",body:"We want to see an inclusive and progressive India where people, especially women and children, can live with dignity, opportunity and freedom from discrimination and exploitation. Our role is to help communities take part in that change through knowledge, conversation and practical support."},
    {title:"Our mission",body:"We work with communities through education, awareness, skill development and creative communication. We address urgent social and public-health concerns while protecting the language, art and cultural heritage that help people understand who they are."},
    {title:"The principles behind our work",body:"These commitments guide how we plan programmes, choose partners and treat the people who take part.",bullets:["Dignity and empathy","Equality and inclusion","Integrity and accountability","Participation and informed choice","Creativity with purpose","Respect for culture and community knowledge","Collaboration that adds real value"]},
    {title:"Punjabi Samvad today",body:"Headquartered in Amritsar, Punjabi Samvad remains grounded in the communities where its work began while developing partnerships with a wider national outlook. President Jyoti Bawa leads the organisation and continues the work she began with Amit Bawa. The aim remains clear: address neglected issues with honesty, create space for participation and build programmes that people can use."}
  ],cta:{label:"Read our full story",href:"/our-story"}},
  "our-story": { eyebrow:"Since 2004",title:"Our Story",intro:"Punjabi Samvad began when Amit Bawa and Jyoti Bawa chose to act on gender-based violence and discrimination.",sections:[
    {title:"A platform for difficult conversations",body:"One of the earliest initiatives was Khooh Bolda Hai, a theatre production written and directed by Jyoti Bawa. Addressing female foeticide and gender discrimination, it established creative advocacy at the heart of the organisation.",stat:"1,100,000+ people reached"},
    {title:"The work expanded",body:"Educational and vocational programmes created opportunities for women, girls and young people. Health work addressed HIV/AIDS and menstrual health; mental-health sessions entered schools and communities; anti-drug programmes combined lectures, outreach and film."},
    {title:"Continuing the work",body:"After Amit Bawa’s passing in 2014, Jyoti Bawa continued the work they began together and now serves as President."},
    {title:"Our journey",body:"From grassroots theatre to programmes at greater scale and a wider national focus.",bullets:["2004 — Punjabi Samvad begins","2009 — Formal registration","2017 — Tirhayi Umar documentary and World Punjabi Conference","Recent years — 100,000+ reached through mental-health programmes","Today — Partnerships for a wider national reach"]}
  ],cta:{label:"Explore our work",href:"/our-work"}},
  "our-work": { eyebrow:"Focus areas",title:"What We Work On",intro:"Our focus areas are connected by one principle: people need clear information, practical opportunity and a safe place to speak. We work in schools, communities and institutions, adapting each programme to the people, issue and setting.",sections:[
    {title:"Women & Girls",body:"We support women and girls through education, skills, health awareness and public discussion about discrimination. The work addresses immediate barriers while building the knowledge and confidence needed to participate in family, community and economic life.\n\nRecent vocational sessions for rural girls and women from families affected by substance abuse covered soap making, traditional masala preparation, spice-quality checks and Phulkari embroidery. Other activities include scholarship support, menstrual-health education and creative campaigns on gender equality and the dignity of girls.",bullets:["Educational and scholarship support","Vocational learning and practical skills","Menstrual-health information","Gender equality and female-foeticide awareness"]},
    {title:"Education & Youth",body:"Young people need more than classroom instruction. They need guidance, exposure and opportunities to apply what they learn. Punjabi Samvad works with students through mentoring, internships, awareness sessions, cultural participation and practical learning.\n\nProgrammes encourage young people to ask questions, understand social concerns and take responsible roles within their schools and communities.",bullets:["Mentoring and learning assistance","Internships and field exposure","Vocational and life-skills learning","Youth participation in community initiatives"]},
    {title:"Mental Health",body:"Mental-health literacy helps people recognise emotional distress, speak without shame and seek appropriate support. Our school and community sessions introduce clear, age-appropriate information and challenge the idea that emotional difficulty should remain hidden.\n\nWhere programmes are delivered with specialist partners, subject expertise is combined with Punjabi Samvad’s experience of community engagement.",stat:"100,000+ people reached",bullets:["School and community awareness sessions","Stigma reduction and open discussion","Information on recognising distress","Guidance towards appropriate support"]},
    {title:"Menstrual Health & Hygiene",body:"Misinformation around menstruation can affect health, school participation and confidence. Our sessions create a respectful setting in which girls and women can ask practical questions and receive reliable, understandable information.\n\nThe work also engages schools and communities so that menstrual health is treated as a normal health and dignity issue rather than a source of embarrassment.",stat:"15,000+ people reached",bullets:["Practical menstrual-health education","Myth and stigma reduction","Hygiene and well-being information","Dialogue with schools and communities"]},
    {title:"Substance-Abuse Awareness",body:"Prevention begins before addiction takes hold. Punjabi Samvad works with students, families and communities to explain the personal, social and economic consequences of substance abuse.\n\nLectures and seminars are supported by grassroots outreach and creative communication, including Tirhayi Umar, which brings the human cost of addiction into public view.",stat:"52,000+ people reached",bullets:["Preventive sessions in schools","Community and family awareness","Expert-led lectures and seminars","Documentary and creative communication"]},
    {title:"Community Health",body:"Reliable health information can protect individuals while reducing fear and exclusion. Our community-health work includes HIV/AIDS prevention, testing and treatment awareness, stigma reduction and broader preventive-health outreach.\n\nWe work with public institutions, professionals and community partners to make information accessible and connect awareness with responsible action.",stat:"100+ HIV/AIDS programmes",bullets:["HIV and STI prevention awareness","Testing, treatment and helpline information","Stigma reduction","Preventive-health camps and outreach"]},
    {title:"Art, Culture & Heritage",body:"Art can reach people in ways that formal instruction cannot. Theatre, film, literature and cultural programmes have been part of Punjabi Samvad from the beginning, helping communities discuss gender discrimination, addiction and other difficult subjects.\n\nCultural work also creates opportunities for younger generations to encounter Punjabi language, artistic practice and heritage as living parts of community life.",bullets:["Theatre for public awareness","Documentary storytelling","Literature and writing","Punjabi art and cultural platforms"]}
  ],cta:{label:"View programmes",href:"/programmes"}},
  programmes: { eyebrow:"How we work",title:"Our Programmes",intro:"Our programmes combine credible information with formats people can engage with: workshops, expert sessions, outreach, education, theatre, film and institutional partnerships. Delivery is shaped around the audience, setting and agreed purpose.",sections:[
    {title:"MPower: Mental-Health Awareness",body:"Structured school and community sessions help participants understand mental well-being, recognise signs of distress and replace stigma with informed conversation. The work includes programmes associated with MPower and the Aditya Birla Educational Trust.\n\nSessions are designed to make the subject approachable without oversimplifying it, and to encourage appropriate help-seeking when support is needed.",stat:"100,000+ reached",bullets:["Age-appropriate awareness","Recognising emotional distress","Reducing shame and misinformation","Encouraging informed help-seeking"]},
    {title:"Ujaas: Menstrual Health & Hygiene",body:"Ujaas provides practical menstrual-health education in a setting where participants can ask questions openly. Implemented with the Aditya Birla Educational Trust, the programme addresses myths, hygiene, physical well-being and the social stigma surrounding menstruation.\n\nSchools and communities are part of the conversation because lasting change depends on a supportive environment, not information alone.",stat:"15,000+ reached",bullets:["Reliable, practical information","Myth and stigma reduction","Question-led sessions","School and community engagement"]},
    {title:"Anti-Drug Awareness",body:"This prevention-focused programme reaches students and communities through lectures, seminars and grassroots activity. It explains how substance abuse affects health, families, education and livelihoods, while promoting informed choices before dependency develops.\n\nTirhayi Umar adds documentary storytelling to the programme, showing the human consequences that may be lost in statistics.",stat:"52,000+ people reached",bullets:["School-based prevention","Community outreach","Expert sessions","Creative and documentary advocacy"]},
    {title:"Khooh Bolda Hai",body:"Written and directed by Jyoti Bawa, Khooh Bolda Hai uses theatre to confront female foeticide, gender discrimination and the unequal treatment of girls. Performance creates an emotional and public space for audiences to consider how prejudice operates within families and communities.\n\nThe production remains an important example of Punjabi Samvad’s belief that creative work can begin conversations that conventional awareness material may not.",stat:"1,100,000+ people reached",bullets:["Gender-equality awareness","Theatre-led community dialogue","Dignity and rights of girls","Creative public advocacy"]},
    {title:"Vocational Skills for Rural Girls",body:"Jyoti Bawa first completed vocational training herself and then led sessions for girls and women from rural communities. Participants learned to make soap and traditional masalas, and to check common spices such as black pepper and cardamom for quality and adulteration.\n\nPunjabi Samvad also restarted Phulkari embroidery training. Jyoti funded the sessions with donations and savings from other projects. The work included families affected by substance abuse.\n\nParticipant stories from the programme have been documented so Punjabi Samvad can record their experience, identify gaps in the training and plan suitable follow-up.",bullets:["Soap making and product preparation","Traditional masala preparation","Spice quality and adulteration checks","Phulkari embroidery"]},
    {title:"HIV/AIDS Awareness",body:"HIV/AIDS programmes provide clear information about prevention, testing, treatment and the harm caused by stigma. Sessions encourage responsible health decisions while reinforcing that people living with HIV deserve dignity and access to care.\n\nPunjabi Samvad has worked with public-health institutions and community partners to take this information into accessible local settings.",stat:"100+ programmes",bullets:["Prevention and safer choices","Testing and treatment information","Helpline and referral awareness","Dignity and stigma reduction"]}
  ],cta:{label:"Discuss a partnership",href:"/discuss-partnership"}},
  impact:{eyebrow:"Reach & learning",title:"Our Impact",intro:"Numbers show scale, but they do not tell the whole story. We document delivery and reach, listen to participant response and use available evidence to improve how programmes are designed and implemented.",sections:[
    {title:"Documented programme reach",body:"Our current figures reflect people reached through programmes and activities delivered across major areas of work. They are presented as programme reach rather than claims about long-term personal outcomes.\n\nThis distinction keeps reporting clear and allows partners and communities to understand what each figure represents.",bullets:["100,000+ reached through mental-health programmes","15,000+ reached through menstrual-health programmes","52,000+ reached through anti-drug awareness","100+ HIV/AIDS awareness programmes","1,100,000+ reached through Khooh Bolda Hai"]},
    {title:"How we measure",body:"Reach is one part of impact. Depending on the programme, we also examine participation, questions raised, feedback and changes in awareness where suitable measurement tools are available.\n\nWe distinguish between an activity delivered, a participant reached, a change in knowledge and a longer-term outcome. Each requires different evidence.",bullets:["People reached and sessions delivered","Schools, villages and communities covered","Participant engagement and feedback","Changes in awareness where measurement tools are used","Programme learning and areas for improvement"]},
    {title:"What participation tells us",body:"Questions and feedback reveal what people already know, where misinformation persists and which parts of a session feel useful. This qualitative information helps facilitators adjust language, examples and future delivery.\n\nThe recent vocational programme also produced beneficiary case studies from rural girls and families affected by substance abuse. These accounts record participant experience, identify gaps in the training and inform follow-up without exposing personal details."},
    {title:"Learning with partners",body:"Institutional and subject partners contribute expertise, delivery support and additional perspective. Programme review allows that shared knowledge to be used in future planning, especially when work is adapted for a new school, community or location.\n\nWe aim to carry forward what worked while remaining honest about what needs to change."},
    {title:"How information improves programmes",body:"Programme information is used to refine content, prepare facilitators, choose suitable formats and identify where follow-up may be valuable. It also supports clearer conversations with funders and implementation partners about scope, resources and realistic outcomes.",bullets:["Improve session content and delivery","Identify recurring knowledge gaps","Plan responsible follow-up","Adapt programmes without losing their purpose","Report reach and learning clearly"]}
  ],cta:{label:"View programmes",href:"/programmes"}},
  leadership:{eyebrow:"Our leadership",title:"About the President",intro:"Meet Jyoti Bawa, Padma Shri nominee, TEDx speaker, social activist, writer and director leading Punjabi Samvad.",sections:[
    {title:"Programme leadership",body:"Part of Punjabi Samvad since 2004, Jyoti Bawa leads work across women’s empowerment, education, public health, mental well-being, substance-abuse awareness and Punjabi culture."},
    {title:"Theatre, writing & documentary",body:"She wrote and directed Khooh Bolda Hai and has used writing, poetry, books, documentary storytelling and other creative formats for social awareness.",stat:"1,100,000+ people reached"},
    {title:"Cultural work",body:"For more than a decade she has helped organise platforms celebrating Punjabi art and culture. In 2017, she represented Punjabi culture at the World Punjabi Conference in Canada."},
    {title:"Continuing Punjabi Samvad",body:"After Amit Bawa’s passing in 2014, Jyoti Bawa continued the work they started and now leads the organisation’s wider national focus."}
  ],cta:{label:"Read our story",href:"/our-story"}},
  partners:{eyebrow:"Shared purpose",title:"Partners & Collaborations",intro:"We work with government, education, charitable, professional and corporate partners to add expertise, resources and reach.",sections:[
    {title:"Aditya Birla Educational Trust",body:"Documented collaboration through MPower mental-health awareness and Ujaas menstrual-health awareness."},
    {title:"Government of Punjab",body:"Public-health and social-awareness activities, including HIV/AIDS awareness."},
    {title:"Ministry of Culture",body:"Engagement connected with culture and heritage initiatives."},
    {title:"IIM Amritsar",body:"Internships connecting academic learning with exposure to social and community work."},
    {title:"CMS Foundation",body:"A formal collaboration supporting community-based social programmes, including substance-abuse awareness in Punjab."},
    {title:"Techvimal Foundation",body:"A partner organisation connected with Punjabi Samvad’s social-impact work and institutional outreach."},
    {title:"Ministry of Information & Broadcasting",body:"Institutional engagement connected with public-interest communication and awareness."},
    {title:"Department of Health & Family Welfare, Punjab",body:"Collaboration connected with public-health awareness and community outreach in Punjab."},
    {title:"Work with us",body:"We welcome CSR teams, foundations, government institutions, schools, universities, healthcare professionals and social-sector organisations."}
  ],cta:{label:"Discuss a partnership",href:"/discuss-partnership"}},
  "csr-partnerships":{eyebrow:"Institutional collaboration",title:"CSR & Institutional Partnerships",intro:"More than two decades of grassroots experience, community engagement and creative communication for programmes across India.",sections:[
    {title:"Areas of partnership",body:"Programmes can be developed around agreed needs and outcomes.",bullets:["Women and girls","Mental health and youth well-being","Community health and substance-abuse prevention","Theatre and creative awareness"]},
    {title:"Ways we can work together",body:"Flexible models shaped around programme scope.",bullets:["Programme implementation","Awareness and education campaigns","Creative communication","Expert engagement","Academic collaboration","Multi-location programmes"]},
    {title:"Why Punjabi Samvad",body:"Grassroots experience, institutional collaboration, rural and semi-urban engagement, creative capability and documented reach.",bullets:["CSR Registration: CSR00032253","12AB registered","80G approved","National programme outlook"]}
  ],cta:{label:"Discuss a partnership",href:"/discuss-partnership"}},
  "fund-a-programme":{eyebrow:"Targeted support",title:"Fund a Programme",intro:"Support a specific area of Punjabi Samvad’s work. We can share current priorities and discuss where funding is most useful.",sections:[
    {title:"Women & Girls",body:"Girls’ education, vocational skills, menstrual-health and gender-awareness programmes."},{title:"Mental Health",body:"Extend awareness programmes to more schools and communities."},{title:"Menstrual Health",body:"Help more girls access reliable menstrual-health information."},{title:"Education & Youth",body:"Educational assistance, mentoring, vocational development and youth activities."},{title:"Substance-Abuse Awareness",body:"Lectures, outreach and preventive communication in additional communities."},{title:"Community Health",body:"HIV/AIDS and preventive-health education."},{title:"Culture & Creative Advocacy",body:"Theatre, cultural programmes and social communication."}
  ],cta:{label:"Contact us about funding",href:"/contact"}},
  "discuss-partnership":{eyebrow:"Start a conversation",title:"Discuss a Partnership",intro:"Tell us about your social-impact programme, target group, geography and current stage. We can explore whether Punjabi Samvad is the right implementation partner.",sections:[
    {title:"What are you exploring?",body:"We welcome early conversations as well as detailed programme briefs.",bullets:["CSR partnership","Foundation grant","Programme sponsorship","Employee engagement","Academic collaboration","Multi-state programme"]},
    {title:"Areas of interest",body:"Women and girls, mental health, menstrual health, education, substance-abuse awareness, community health, culture or multiple areas."},
    {title:"Geographic scope",body:"One community, one state, multiple states or pan-India programmes can be discussed based on requirements and local implementation needs."}
  ],cta:{label:"Email our partnership team",href:"mailto:punjabisamvadasr@gmail.com?subject=Partnership%20Enquiry"}},
  "get-involved":{eyebrow:"Internships and volunteering",title:"Internships & Volunteering",intro:"University students can gain practical experience through social research, programme delivery, communication and community engagement with Punjabi Samvad.",sections:[
    {title:"Community programmes",body:"Support awareness sessions, outreach and programme preparation under the guidance of the Punjabi Samvad team."},
    {title:"Research and documentation",body:"Assist with background research, programme records, participant feedback and material for future planning."},
    {title:"Literature and communication",body:"Contribute to literary campaigns, cultural work, educational material and digital awareness."},
    {title:"Volunteer and professional support",body:"People with relevant time or expertise may support events, training, health education, arts and programme planning."}
  ],cta:{label:"Apply or enquire",href:"mailto:punjabisamvadasr@gmail.com?subject=Internship%20or%20Volunteer%20Enquiry"}},
  support:{eyebrow:"Make change possible",title:"Support Our Work",intro:"Donations help sustain current work and extend programmes where additional resources are available.",sections:[
    {title:"Support a specific programme",body:"Choose an area aligned with your interests and discuss current priorities with us."},
    {title:"Support where needed",body:"Unrestricted contributions allow flexibility to respond to current programme and organisational needs."},
    {title:"CSR & institutional funding",body:"Structured partnerships can support clearly defined programmes across one or multiple locations."},
    {title:"80G approval",body:"Eligible donations may qualify for tax benefits under applicable provisions. Please consult your tax adviser."}
  ],cta:{label:"Contact us to support",href:"/contact"}},
  gallery:{eyebrow:"Our work in pictures",title:"Gallery",intro:"Photographs from programmes, workshops, community activities, cultural events and partnerships.",sections:[
    {title:"Women & Girls",body:"Education, vocational skills and awareness activities."},{title:"Health & Well-being",body:"Mental-health, menstrual-health and HIV/AIDS awareness."},{title:"Substance-Abuse Awareness",body:"Lectures, seminars and community outreach."},{title:"Education & Youth",body:"Student engagement, internships, mentoring and participation."},{title:"Culture & Theatre",body:"Theatre productions, cultural programmes and artistic activities."},{title:"Community & Partnerships",body:"Grassroots work and institutional collaborations."}
  ],cta:{label:"Explore our programmes",href:"/programmes"}},
  updates:{eyebrow:"Latest",title:"News & Updates",intro:"Latest news and activities from Punjabi Samvad.",sections:[
    {title:"Mental-Health Awareness in Schools",body:"Making emotional well-being easier for young people to understand and discuss.",stat:"100,000+ reached"},{title:"Menstrual-Health Awareness",body:"Practical information addressing stigma and misinformation.",stat:"15,000+ reached"},{title:"Anti-Drug Awareness in Rural Communities",body:"Grassroots lectures and Tirhayi Umar communicate the human impact of substance abuse.",stat:"52,000+ reached"},{title:"Khooh Bolda Hai",body:"Theatre addressing female foeticide, discrimination and dignity.",stat:"1,100,000+ reached"},{title:"Education for Girls",body:"Educational support and initiatives intended to reduce barriers to learning."},{title:"Punjabi Culture & Youth",body:"Creative platforms connecting young people with Punjabi heritage."}
  ]},
  transparency:{eyebrow:"Accountability",title:"Transparency & Compliance",intro:"Clear information about Punjabi Samvad’s legal status, registrations and approvals.",sections:[
    {title:"Organisation details",body:"Registered under the Societies Registration Act, 1860.",bullets:["Registration No. 75","Registered 02 July 2009","PAN: AACAP2577N","NGO Darpan: PB/2017/0156494","CSR Registration: CSR00032253","Registered office: 293, Green Avenue, Amritsar, Punjab 143001"]},
    {title:"12AB Registration",body:"Granted under Section 12AB(1)(b).",bullets:["Registration: AACAP2577N25CD01","Approval date: 06 March 2026","Assessment years: 2027–28 to 2036–37"]},
    {title:"80G Approval",body:"Approved under Section 80G(5).",bullets:["Approval: AACAP2577N25CD01","Approval date: 06 March 2026","Assessment years: 2027–28 to 2031–32"]},
    {title:"Documents",body:"Registration certificate, CSR registration, NGO Darpan registration, 12AB and 80G approval orders are maintained by the organisation."}
  ],cta:{label:"Request information",href:"/contact"}},
  faq:{eyebrow:"Useful information",title:"Frequently Asked Questions",intro:"Quick answers about Punjabi Samvad, our programmes, partnerships and ways to contribute.",sections:[
    {title:"What is Punjabi Samvad?",body:"A national NGO headquartered in Amritsar working across empowerment, education, mental health, menstrual health, youth, substance-abuse awareness, HIV/AIDS and culture."},
    {title:"When did Punjabi Samvad begin?",body:"The journey began in 2004 with Amit Bawa and Jyoti Bawa. Formal registration followed on 02 July 2009."},
    {title:"Where do you work?",body:"Our grassroots experience is rooted in Punjab, while we welcome partnerships with a wider national and multi-state focus."},
    {title:"Can companies partner for CSR programmes?",body:"Yes. Punjabi Samvad holds CSR Registration No. CSR00032253."},
    {title:"Can I fund a specific programme?",body:"Yes, depending on current priorities. Contact us to discuss the work you want to support."},
    {title:"Do you accept volunteers and interns?",body:"Yes, subject to current programmes, locations and requirements."},
    {title:"Do you have 80G approval?",body:"Yes. Eligible donations may qualify for tax benefits under applicable provisions."}
  ],cta:{label:"Ask another question",href:"/contact"}},
  contact:{eyebrow:"Start a Samvad",title:"Contact Punjabi Samvad",intro:"Discuss a programme, partnership, donation, volunteer opportunity, internship or general enquiry.",sections:[
    {title:"Registered office",body:"293, Green Avenue\nAmritsar, Punjab 143001\nIndia"},
    {title:"Phone & email",body:"+91 87280 33911\npunjabisamvadasr@gmail.com"},
    {title:"Contact person",body:"Jyoti Bawa\nPresident, Punjabi Samvad"},
    {title:"What can you help with?",body:"CSR partnership, institutional collaboration, national programmes, volunteering, internships, programme information, support, media or events."}
  ],cta:{label:"Send an email",href:"mailto:punjabisamvadasr@gmail.com"}}
};
